### ISSUE TITLE
Custom filter for participants with 1+ non-normal value

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#45]
# Test notes
* A checkbox appears beneath the x-axis dropdown labeled _Inliers_ that toggles the display of participants in each chart without values outside the normal range.

**Comment by emmorris** [comment]
Hide normal participants in order to improve performance.
Opaque-ify normal range.
Only works with normal ranges.
Add checkbox to display all participants.
Consider data-driven outliers (extrapolate normal range).

Karen K. requested that we make the default for hiding normal participants dependent on the amount of data since normal participant data is very useful when the data set is small.
